### ISSUE TITLE
sadly doesnt work with kali 2020

### ISSUE THREAD

**Issue by kyleAW** [SafeBreach-Labs/SirepRAT#12]
as its written in 2.7 it wont work on kali 2020 as its no longer supported so pip only works for python 3 not 2.7

**Comment by pwnfoo** [comment]
@kyleAW `python2 -m pip` should work.

**Comment by dorazouri** [comment]
@kyleAW will happily accept PRs for porting into python3

**Comment by dorazouri** [comment]
@kyleAW SirepRAT v2 is now committed and supports python3! See latest code and [release](https://github.com/SafeBreach-Labs/SirepRAT/releases/tag/v2.0.0).
