### ISSUE TITLE
[Chore] setup.py

### ISSUE THREAD

**Issue by noraj** [SafeBreach-Labs/SirepRAT#13]
Hi,

Could you provide a setup.py please?

https://packaging.python.org/tutorials/packaging-projects/#creating-setup-py

**Comment by dorazouri** [comment]
Created a setup.py for packaging

**Comment by noraj** [comment]
Nice thanks but it lacks of an entry point https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html
