### ISSUE TITLE
python3 SyntaxError

### ISSUE THREAD

**Issue by issayevruslan** [SafeBreach-Labs/SirepRAT#14]
File "SirepRAT.py", line 98
    print "RECV:"
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("RECV:")?

**Comment by darkore0** [comment]
I have the same exact problem.

**Comment by dorazouri** [comment]
The project was built and supports **python2.7** only,
Luckily @movatica has just recently started porting it to **python3**.
Please follow this pull request to follow progress and contribute: #10
