### ISSUE TITLE
'int' object has no attribute 'value'

### ISSUE THREAD

**Issue by ShamanCoder** [SafeBreach-Labs/SirepRAT#15]
Tried to run the program on kali with python 2.7, get this output:

`Traceback (most recent call last):
  File "SirepRAT.py", line 52, in <module>
    from common.mappings import SIREP_COMMANDS, RESULT_TYPE_TO_RESULT
  File "/home/drsuius/PortableTools/Python/SirepRAT/common/mappings.py", line 65, in <module>
    ResultRecordType.SystemInformation.value: results.SystemInformationResult,
AttributeError: 'int' object has no attribute 'value'`

**Comment by ShamanCoder** [comment]
solved by removing the enum library and installing the enum34 library

**Comment by dorazouri** [comment]
@ShamanCoder SirepRAT v2 is now committed and supports python3! See latest code and [release](https://github.com/SafeBreach-Labs/SirepRAT/releases/tag/v2.0.0).
