### ISSUE TITLE
No module named common.constants

### ISSUE THREAD

**Issue by umiterkol** [SafeBreach-Labs/SirepRAT#3]
python SirepRAT.py 
Traceback (most recent call last):
  File "SirepRAT.py", line 49, in <module>
    from common.constants import SIREP_VERSION_GUID_LEN, LOGGING_FORMAT, LOGGING_LEVEL, SIREP_PORT, INT_SIZE, \
ImportError: No module named common.constants

**Comment by dorazouri** [comment]
Seems like a path inclusion issue. Either add your cloned directory to the PATH system variable, or use sys.path.insert(0, path)
