### ISSUE TITLE
mappings.py line 65: AttributeError: 'int' object has no attribute 'value'

### ISSUE THREAD

**Issue by jbdu94** [SafeBreach-Labs/SirepRAT#4]
Hello

When I run the following command, I have the following error

python SirepRAT.py 10.10.xx.xx  LaunchCommandWithOutput --return_output --cmd "C:\Windows\System32\cmd.exe" --args "/c powershell.exe ipconfig" --v
Traceback (most recent call last):
  File "SirepRAT.py", line 52, in <module>
    from common.mappings import SIREP_COMMANDS, RESULT_TYPE_TO_RESULT
  File "/home/tomski/HTB/SirepRAT/common/mappings.py", line 65, in <module>
    ResultRecordType.SystemInformation.value: results.SystemInformationResult,
AttributeError: 'int' object has no attribute 'value'

Could you please help me to fix it?

**Comment by 0xMohammed** [comment]
pip uninstall enum
pip install enum34

**Comment by jbdu94** [comment]
Thx !!!

**Comment by gearcapitan** [comment]
![imagen](https://user-images.githubusercontent.com/13740942/97934646-df34fd80-1d3b-11eb-8413-8e95fb163dda.png)
the problem persist

**Comment by dorazouri** [comment]
> ![imagen](https://user-images.githubusercontent.com/13740942/97934646-df34fd80-1d3b-11eb-8413-8e95fb163dda.png)
> the problem persist

Hi, please see issue #2 for the solution.
Also - latest requirements.txt does specify enum34 explicitly, so that should do the work:
`pip install -r requirements.txt`
