### ISSUE TITLE
AttributeError: 'int' object has no attribute 'value'

### ISSUE THREAD

**Issue by tomdoughty62** [SafeBreach-Labs/SirepRAT#8]
Hello,

I've tried using SirepRAT on ParrotOS and the ARM version of Kali, and I keep getting the following error:

Traceback (most recent call last):
  File "SirepRAT.py", line 52, in <module>
    from common.mappings import SIREP_COMMANDS, RESULT_TYPE_TO_RESULT
  File "/root/hackthebox/Omni/SirepRAT/common/mappings.py", line 65, in <module>
    ResultRecordType.SystemInformation.value: results.SystemInformationResult,
AttributeError: 'int' object has no attribute 'value'

Can you please advise me on how to solve this issue?

Thank you.

**Comment by dorazouri** [comment]
Hi, please see issue #2 for the solution.
Also - latest requirements.txt does specify enum34 explicitly, so that should do the work:
`pip install -r requirements.txt`

**Comment by gearcapitan** [comment]
![imagen](https://user-images.githubusercontent.com/13740942/97934497-86656500-1d3b-11eb-8e95-0c078e3b8eb8.png)
same problem

**Comment by dorazouri** [comment]
> ![imagen](https://user-images.githubusercontent.com/13740942/97934497-86656500-1d3b-11eb-8e95-0c078e3b8eb8.png)
> same problem

Hi, please see issue #2 for the solution.
Also - latest requirements.txt does specify enum34 explicitly, so that should do the work:
```pip install -r requirements.txt```

**Comment by dorazouri** [comment]
@tomdoughty62 SirepRAT v2 is now committed and supports python3! See latest code and [release](https://github.com/SafeBreach-Labs/SirepRAT/releases/tag/v2.0.0).
