### ISSUE TITLE
can't run the script

### ISSUE THREAD

**Issue by Dadolikes74** [SafeBreach-Labs/SirepRAT#9]
when i changed the code for exec it with python3, i get this error, i have installed all packages from pip, this is the error

`Traceback (most recent call last):
  File "SirepRAT.py", line 52, in <module>
    from common.mappings import SIREP_COMMANDS, RESULT_TYPE_TO_RESULT
  File "/home/dadolikes74/ctf-htb/omni/SirepRAT/common/mappings.py", line 41, in <module>
    from enums.CommandType import CommandType
ModuleNotFoundError: No module named 'enums.CommandType'; 'enums' is not a package
`

**Comment by DahmounLahcen** [comment]
try to replace   :   **from enums.CommandType import CommandType** by this one :   **from .enums.CommandType import CommandType**

**Comment by RolEYder** [comment]
Try to install enums with `pip install enums`

**Comment by dorazouri** [comment]
That might do the work:
`pip uninstall enum
pip install enum34`

Also - latest requirements.txt does specify enum34 explicitly, so that should install it automatically:
`pip install -r requirements.txt`
